apps/financas/urls.py
from django.urls import path
from .views import (home, CategoriaCreateView, CategoriaDetailView, CategoriaListView, CategoriaUpdateView,
                    DespesaCreateView, DespesaDetailView, DespesaListView, DespesaUpdateView, CarroQuery, 
                    LivroQuery, ComprasQuery, AnimalQuery)

app_name = "financas"

urlpatterns = [
    path('', home, name='home'),
    path('categorias/new', CategoriaCreateView.as_view(), name='categoria-new'),
    path('categorias/list', CategoriaListView.as_view(), name='categoria-list'),
    path('categorias/update/<int:pk>', CategoriaUpdateView.as_view(), name='categoria-update'),
    path('categorias/detail/<int:pk>', CategoriaDetailView.as_view(), name='categoria-detail'),
    path('despesas/new', DespesaCreateView.as_view(), name='despesa-new'),
    path('despesas/list', DespesaListView.as_view(), name='despesa-list'),
    path('despesas/update/<int:pk>', DespesaUpdateView.as_view(), name='despesa-update'),
    path('despesas/detail/<int:pk>', DespesaDetailView.as_view(), name='despesa-detail'),
    path('despesas/list/carro', CarroQuery.as_view(), name='despesa-list-carro'),
    path('despesas/list/livros', LivroQuery.as_view(), name='despesa-list-livro'),
    path('categorias/list/compras', ComprasQuery.as_view(), name='categoria-list-comida'),
    path('despesa/list/animais', AnimalQuery.as_view(), name='despesa-list-animal'),
]

beta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.financas.urls', namespace='financas'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/financas/models.py
from django.db import models

# Create your models here.
from django.db import models

# Create your models here.
class Categoria(models.Model):
    nome = models.CharField(max_length=50)
    imagem = models.ImageField(upload_to='uploads_categorias', default='default_categoria.jpg')

    def __str__(self):
        return self.nome

class Despesa(models.Model):
    categoria = models.ForeignKey(Categoria, on_delete = models.CASCADE)
    descricao = models.CharField(max_length=50)
    valor = models.DecimalField(decimal_places=2, max_digits=6)

    def __str__(self):
      return f'{self.descricao} - {self.valor} €'

apps/financas/views.py
from django.shortcuts import render
from django.db.models import Sum
from django.views.generic import CreateView, UpdateView, DetailView, ListView
from django.urls import reverse_lazy
from .models import Categoria, Despesa

# Create your views here.
def home(request):
    categoria_carro = Categoria.objects.get(nome = 'Carro')
    valor_carro = Despesa.objects.filter(categoria__nome = 'Carro').aggregate(total=Sum('valor'))
    categoria_livros = Categoria.objects.get(nome = 'Livros')
    valor_livros = Despesa.objects.filter(categoria__nome = 'Livros').aggregate(total=Sum('valor'))
    return render(request, 'financas/home.html', context={'valor_carro':valor_carro, 'categoria_carro':categoria_carro, 'valor_livros':valor_livros, 'categoria_livros':categoria_livros})

class CategoriaCreateView(CreateView):
    model = Categoria
    fields = '__all__'
    success_url = reverse_lazy('financas:categoria-list')

class CategoriaListView(ListView):
    model = Categoria

class CategoriaUpdateView(UpdateView):
    model = Categoria    
    fields = '__all__'
    success_url = reverse_lazy('financas:categoria-list')

class CategoriaDetailView(DetailView):
    model = Categoria

class DespesaCreateView(CreateView):
    model = Despesa
    fields = '__all__'
    success_url = reverse_lazy('financas:despesa-list')

class DespesaListView(ListView):
    model = Despesa

    def get_context_data(self, **kwargs): 
        ctx = super().get_context_data(**kwargs)
        ctx['total'] = Despesa.objects.aggregate(a=Sum('valor'))
        return ctx

class DespesaUpdateView(UpdateView):
    model = Despesa    
    fields = '__all__'
    success_url = reverse_lazy('financas:despesa-list')

class DespesaDetailView(DetailView):
    model = Despesa

class CarroQuery(ListView):
    model = Despesa
    queryset = Despesa.objects.filter(categoria__nome='Carro')
    template_name = 'financas/despesa_list.html'

    def get_context_data(self, **kwargs): 
        ctx = super().get_context_data(**kwargs)
        ctx['total'] = Despesa.objects.filter(categoria__nome = 'Carro').aggregate(a=Sum('valor'))
        return ctx

class LivroQuery(ListView):
    model = Despesa
    queryset = Despesa.objects.filter(categoria__nome='Livros')
    template_name = 'financas/despesa_list.html'

    def get_context_data(self, **kwargs): 
        ctx = super().get_context_data(**kwargs)
        ctx['total'] = Despesa.objects.filter(categoria__nome = 'Livros').aggregate(a=Sum('valor'))
        return ctx

class ComprasQuery(ListView):
    model = Despesa
    queryset = Despesa.objects.filter(categoria__nome='Compras')
    template_name = 'financas/categoria_list.html'

    def get_context_data(self, **kwargs): 
        ctx = super().get_context_data(**kwargs)
        ctx['total'] = Despesa.objects.filter(categoria__nome = 'Compras').aggregate(a=Sum('valor'))
        return ctx 

class AnimalQuery(ListView):
    model = Despesa
    queryset = Despesa.objects.filter(categoria__nome='Animais')
    template_name = 'financas/despesa_update.html'

    def get_context_data(self, **kwargs): 
        ctx = super().get_context_data(**kwargs)
        ctx['total'] = Despesa.objects.filter(categoria__nome = 'Animais').aggregate(a=Sum('valor'))
        return ctx                  

apps/financas/templates/financas/categoria_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Categoria</legend>
                <div class="form-group" style="padding-bottom: 10px;">
                        {{ form|crispy }}
                </div>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-primary" type="submit">Guardar</button>
            </div>
        </form>
    </div>
{% endblock content %}

apps/financas/templates/financas/categoria_list.html
{% extends "base.html" %}

{% block content %}
<h4>Criar novo <a class="btn btn-outline-primary" href="{% url 'financas:categoria-new' %}"><i class="fa-solid fa-plus"></i></a></h4>
<h3>Categorias</h3>
<table class="table">
    <tr>
        <th style="width: 60px;">Imagem</th>
        <th>Nome</th>
    </tr>
    {% for object in object_list %}
        <tr>
            <td style="width: 60px;"><img src="{{ object.imagem.url }}" height="20px"></td>
            <td>{{ object.nome }}</td>
        </tr>
    {% endfor %}
</table>
{% endblock content %}

apps/financas/templates/financas/despesa_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Despesa</legend>
                <div class="form-group" style="padding-bottom: 10px;">
                        {{ form|crispy }}
                </div>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-primary" type="submit">Guardar</button>
            </div>
        </form>
    </div>
{% endblock content %}

apps/financas/templates/financas/despesa_list.html
{% extends "base.html" %}

{% block content %}
<a class="btn btn-primary" href="{% url 'financas:despesa-new' %}">Novo</a>
<h3>Despesas</h3>
<table class="table">
    <tr>
        <th>Imagem</th>
        <th>Categoria</th>
        <th>Descrição</th>
        <th>Valor</th>
    </tr>
    {% for object in object_list %}
        <tr>
            <td style="width: 40px;"><img src="{{ object.categoria.imagem.url }}" height="20px"></td>
            <td>{{ object.categoria }}</td>
            <td>{{ object.descricao }}</td>
            <td>{{ object.valor }}€</td>
        </tr>
    {% endfor %}
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td><b>{{ total.a|floatformat:2 }}€</b></td>
    </tr>
</table>
{% endblock content %}

apps/financas/templates/financas/home.html
{% extends "base.html" %}

{% block content %}
<style>
    .card:hover{
        background-color:rgb(197, 129, 2);
        transition-duration: 0.7s;
        color: white;
        }
</style>
<div class="row">
    <div class="col-3">
        <a href="{% url 'financas:despesa-list-carro' %}" style="text-decoration: none; color: blue;">
            <div class="card" style="height: 300px;">
                <img src="{{ categoria_carro.imagem.url }}" class="card-img-top" height="200px">
                <div class="card-body" style="text-align: center;">
                    <h3>{{categoria_carro.nome}}</h3>
                    <!-- <p class="card-text">{{ valor_consulta.total|floatformat:2 }}€</p> -->
                </div>
            </div>
        </a>
    </div>
    <div class="col-3">
        <a href="{% url 'financas:despesa-list-livro' %}" style="text-decoration: none; color: blue">
            <div class="card" style="height: 300px;">
                <img src="{{ categoria_livros.imagem.url }}" class="card-img-top" height="200px">
                <div class="card-body" style="text-align: center;">
                    <h3>{{categoria_livros.nome}}</h3>
                    <!-- <p class="card-text">{{ valor_consulta.total|floatformat:2 }}€</p> -->
                </div>
            </div>
        </a>
    </div>
    <br>
    <div class="col-3">
        <a href="{% url 'financas:categoria-list-comida' %}" style="text-decoration: none; color: blue">
            <div class="card" style="height: 300px;">
                <img src="../media/uploads_categorias/compras.jpg" class="card-img-top" height="200px">
                <div class="card-body" style="text-align: center;">
                    <h3>Compras</h3>
                    <!-- <p class="card-text">{{ valor_consulta.total|floatformat:2 }}€</p> -->
                </div>
            </div>
        </a>
    </div>
    <div class="col-3">
        <a href="{% url 'financas:despesa-list-animal' %}" style="text-decoration: none; color: blue">
            <div class="card" style="height: 300px;">
                <img src="../media/uploads_categorias/animais.jpg" class="card-img-top" height="200px">
                <div class="card-body" style="text-align: center;">
                    <h3>Animais</h3>
                    <!-- <p class="card-text">{{ valor_consulta.total|floatformat:2 }}€</p> -->
                </div>
            </div>
        </a>
    </div>
</div>
{% endblock %}

templates/base.html
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-expand-sm" style="background-color: #0c2aec;">
            <div class="container-fluid">
                <a class="navbar-brand" style="color: White;">Tarefa 11.10.2022<br>Gestão de despesas</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'financas:home' %}" style="color: White;">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'financas:categoria-list' %}" style="color: White;">Categorias</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'financas:despesa-list' %}" style="color: White;">Despesas</a>
                    </li>
                </ul>
                <p style="color: White;">Data final de entrega 16.10.2022</p>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder=" " aria-label="Search">
                    <button class="btn btn-outline-success" type="submit" style="color: White;">Search</button>
                  </form>
              </div>
            </div>
        </nav>
        <h3>Aplicação realizada no UFCD 5417 como tarefa final</h3><br><br>

        <div style="padding: 30px">
            {% block content %}{% endblock %}
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
        <br>
        <br>
        <br>
        <h3 style="padding-left: 1600px;" >Formador: Rodrigo Cid</h3>
        <br>
        <h3 style="padding-left: 1560px;">Formando: Martin Argirov</h3>
    </body>
</html>